# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZK4LrHe043ffoPkIRCoAXLIJ96l-PsQ
"""

class cashieringsystem:

  def __init__(self, a = 0, r = 0, recieve = 0, change = 0, temp = 0):
    print("\n\n****Welcome to simple cashiering system****\n")

    self.a = a 
    self.r = r
    self.recieve = recieve 
    self.change = change 
    self.temp = temp 

  def foods(self):
    print("****My Restaurent Menu****")

    print("1.Kacchi----&bdt;18", "\n2.Coffee----&bdt;25", "\n3.Alur Chop----&bdt;5", "\n4.Tea----&bdt;8" "\n5.Cash Out", "\n6. Exit")

    while (1):
      c = int(input("Choose:\n"))

      if (c == 1):
        d = int(input("Enter the quantity:\n"))
        self.r = self.r + 18 * d 

      elif (c == 2):
        d = int(input("Enter the quantity:\n"))
        self.r = self.r + 25 *  d 
      
      elif (c == 3):
        d = int(input("Enter the quantity:\n"))
        self.r = self.r + 5 * d

      elif (c == 4):
        d = int(input("Enter the quantity:\n"))
        self.r = self.r + 8 * d

      elif (c == 5):
        print("total:", self.r)
        if (self.r > 0):
          recieve = int(input("Input Money Recieve:\n"))
          print("Change:", recieve - self.r)
          print("****Thanks a lot. Please Come Again !!****")
          quit()
      
      elif (c == 6):
        quit()
      
      else:
        print('Invalid Option')



def main():
  a = cashieringsystem()

  while (1):
    a.foods()



main()

